# Generated by Django 4.2.3 on 2023-07-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('seats', models.JSONField(default=list)),
            ],
        ),
    ]
